# Generated by Django 3.2.8 on 2022-06-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline_Companie',
            new_name='Airline_Company',
        ),
    ]
