# Generated by Django 3.2.8 on 2022-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220629_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
