# Generated by Django 3.2.8 on 2022-08-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220706_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightAPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_company_id', models.TextField()),
                ('origin_country_id', models.TextField()),
                ('destination_country_id', models.TextField()),
                ('departure_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('landing_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('remaining_tickets', models.IntegerField()),
            ],
        ),
    ]
