# Generated by Django 3.2.8 on 2022-08-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_flight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
    ]
